### ISSUE TITLE
Crash opening non-existent "recent" file

### ISSUE THREAD

**Issue by pont-us** [pont-us/PuffinPlot#130]
Tried to open a file from the recent files menu; it had moved; Puffin crashed.

Build date: UNKNOWN Crash date: 2009-09-24 09:53:57 java.version    1.5.0_16 java.vendor     Sun Microsystems Inc. os.name         Linux os.arch         i386 os.version      2.6.24-19-generic user.name       pont java.lang.NullPointerException at net.talvi.puffinplot.data.file.TwoGeeLoader.<init>(TwoGeeLoader.java:33) at net.talvi.puffinplot.data.Suite.<init>(Suite.java:211) at net.talvi.puffinplot.PuffinApp.openFiles(PuffinApp.java:231) at net.talvi.puffinplot.window.MainMenuBar$7.actionPerformed(MainMenuBar.java:145) ...

**Comment by pont-us** [comment]
```
Bugs Everywhere data:
Created at: 2009-09-23 21:55:44
Status: fixed
Severity: minor
UUID: 98767462-920d-448c-ad49-35c500ba1b2a
Short name: a88/987
Ditz bug index: 128
```

**Comment by pont-us** [comment]
2009-09-23 22:09:00

Suite constructor now checks that files exist and are readable.

UUID: 2094ec2d-3ded-4757-a96a-3ad6f8281086
